### PR TITLE
Add functions for fill and color in ggplot

### PR DESCRIPTION
**Pull request by teejclark**
Hi,

I've added two functions to incorporate color palettes into ggplot.
1) style_scale_color = a color scale, useful for things like scatterplots, etc.
2) style_scale_fill = a fill scale, useful for barplots, histograms, etc.

Current palettes include:
1) main = 3 simple colors from Duck Hunt: blue, green, and pink
2) duckhunt = full Duck Hunt palette
3) cblind = color blind palette
4) gray = gray scale if needed for publications, etc.

To discuss:
- Do we even like these colors?
- Other palettes or combos for spatial data?

Either way, we have a function now.

### CODE REVIEW

**Comment by teejclark** [comment]
I've also added in a function for a basic theme in ggplot. This is based off of the theme_bw() in ggplot, but with removed axis stuff, and bigger text. 

We can mess around with this later according to personal preference.

**Comment by Huh** [comment]
- Examples would be nice in the documentation
- I didn't see that any of the functions were exported, are you intending them to be internal functions?

**Comment by foresthayes** [comment]
There appears to be an issue with the cllr_colors function - I can no longer install the package from GitHub:

```
Error in cllr_colors("azure", "green", "sunset") : 
  could not find function "cllr_colors"
Error : unable to load R code in package ‘collar’
```

**Comment by teejclark** [comment]
hi all, I've fixed things on my new pull request. I'm gonna let it sit and let somebody else merge it if they think it's satisfactory.

1) Function works
2) I added examples in the documentation
3) Set the first function in the script to be the exported function, similar to what we were discussing with Forest's functions

**Pull request merged**
